## 1

In [3]:
function is_valid(e)
    if e[2] == e[3]
        # Si el zorro y la viscacha están del mismo lado, entonces será valido
        # sólo si el gaucho también está de ese lado
        return e[1] == e[3]
    elseif e[3] == e[4]
        # Si la viscacha y la soja están del mismo lado, entonces será valido
        # solo si el gaucho también está de ese lado
        return e[1] == e[3]
    else
        return true
    end
end
        
function sig(e, index)
    e2 = copy(e)
    if e2[1]
        e2[1] = false
        e2[index] = false
    elseif !e2[1]
        e2[1] = true
        e2[index] = true
    end
    return e2
end
            
function es_nuevo(e2, M)
    for e in M
        if e == e2
            return false
        end
    end
    return true
end

es_nuevo (generic function with 1 method)

In [4]:
function s1a(e, M)
    fin = false
    if e == [true; true; true; true]
        fin = true
        return fin, M
    end
    for i in 1:4
        e2 = sig(e, i)
        valido = is_valid(e2)
        nuevo = es_nuevo(e2, M)
        
        if valido && nuevo
            push!(M, e2)
            fin, M = s1a(e2, M)
            if fin
                break
            end
        end
    end
    return fin, M
end

s1a (generic function with 1 method)

In [5]:
# Gaucho, zorro, viscacha, soja
e = [false; false; false; false]
m = Array{Array{Bool, 1}, 1}()

0-element Array{Array{Bool,1},1}

In [6]:
s1a(e, m)

(true, Array{Bool,1}[[true, false, true, false], [false, false, true, false], [true, true, true, false], [false, true, false, false], [true, true, false, true], [false, true, false, true], [true, true, true, true]])

In [7]:
m
# Gaucho, zorro, viscacha, soja

7-element Array{Array{Bool,1},1}:
 [true, false, true, false] 
 [false, false, true, false]
 [true, true, true, false]  
 [false, true, false, false]
 [true, true, false, true]  
 [false, true, false, true] 
 [true, true, true, true]   

In [15]:
[ each for each in Iterators.flatten(m) ]

28-element Array{Bool,1}:
  true
 false
  true
 false
 false
 false
  true
 false
  true
  true
  true
 false
 false
     ⋮
  true
  true
 false
  true
 false
  true
 false
  true
  true
  true
  true
  true

In [14]:
reshape([ each for each in Iterators.flatten(m) ], (7, 4))

7×4 Array{Bool,2}:
  true  false  false   true
 false   true  false  false
  true   true   true   true
 false   true   true   true
 false  false  false   true
 false  false   true   true
  true   true  false   true